# -*- coding: utf-8 -*-
{
    'name': 'CR Medical',
    'summary': 'CR Medical Base Management',
    'version': '1.0',
    'sequence': 1,
    'website': 'https://www.candidroot.com/cr_medical/cr_medical_base',
    'description': """
    

    """,
    'category': 'cr medical base',
    'depends' : ['base', 'product','website'],
    'data': [
        'security/ir.model.access.csv',
        'wizard/update_pharmacy_stock_view.xml',
        'security/security.xml',
        'views/patient_view.xml',
        'views/doctor_view.xml',
        'views/opd_doctor_view.xml',
        'views/opd_patient_view.xml',
        'views/sequence_view.xml',
        'views/doctor_weeklyAvalibility_view.xml',
        'views/doctor_degree_view.xml',
        'views/doctor_speciality_view.xml',
        'views/patient_view.xml',
        'views/doctor_dashboard.xml',
        'views/pharmacy_prescription_view.xml',
        'views/signup_template.xml',
        'views/home_page.xml',
        'views/thankyou_page.xml',
        # 'views/website_doctors.xml',
        'views/website_Doctor1.xml',
        'views/website-doctor_details.xml',
        'views/website_opd_view.xml',
        'views/website_registration.xml',
        'views/website_template_medical.xml',
        'data/menu.xml',
     ],
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': False,
    'auto_install': False,
}
